from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 360)
        self.le6 = QtWidgets.QLineEdit(Dialog)
        self.le6.setGeometry(QtCore.QRect(150, 210, 113, 22))
        self.le6.setObjectName("le6")
        self.le4 = QtWidgets.QLineEdit(Dialog)
        self.le4.setGeometry(QtCore.QRect(150, 140, 113, 22))
        self.le4.setObjectName("le4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.le2 = QtWidgets.QLineEdit(Dialog)
        self.le2.setGeometry(QtCore.QRect(150, 70, 113, 22))
        self.le2.setObjectName("le2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(350, 60, 181, 16))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(350, 30, 291, 21))
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 55, 16))
        self.label_6.setObjectName("label_6")
        self.le5 = QtWidgets.QLineEdit(Dialog)
        self.le5.setGeometry(QtCore.QRect(150, 170, 113, 22))
        self.le5.setObjectName("le5")
        self.le7 = QtWidgets.QLineEdit(Dialog)
        self.le7.setGeometry(QtCore.QRect(150, 240, 113, 22))
        self.le7.setObjectName("le7")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(350, 100, 211, 16))
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 55, 16))
        self.label_3.setObjectName("label_3")
        self.le3 = QtWidgets.QLineEdit(Dialog)
        self.le3.setGeometry(QtCore.QRect(150, 100, 113, 22))
        self.le3.setObjectName("le3")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(350, 310, 93, 28))
        self.ok_btn.setObjectName("ok_btn")
        self.ne_ok_btn = QtWidgets.QPushButton(Dialog)
        self.ne_ok_btn.setGeometry(QtCore.QRect(480, 310, 93, 28))
        self.ne_ok_btn.setObjectName("ne_ok_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Название"))
        self.label_9.setText(
            _translate("Dialog", "text\'; DROP TABLE coffee; --;"))
        self.label_4.setText(_translate("Dialog", "Молотый/ в зёрнах"))
        self.label_8.setText(
            _translate("Dialog", "Пожалуйста, не пишите ничего похожего на"))
        self.label_6.setText(_translate("Dialog", "Цена"))
        self.label_10.setText(
            _translate("Dialog", "Я не хочу экранировать ввод"))
        self.label_5.setText(_translate("Dialog", "Вкус"))
        self.label_7.setText(_translate("Dialog", "Объём"))
        self.label_3.setText(_translate("Dialog", "Обжарка"))
        self.ok_btn.setText(_translate("Dialog", "ok"))
        self.ne_ok_btn.setText(_translate("Dialog", "не ok"))
